name: Release
on:
  # 完整事件列表 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches:
      - main
jobs:
  # 任务1
  release1:
    name: Release1
    # 虚拟机环境，可用环境 https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    # 依赖release2
    needs: [release2]
    # 具体步骤
    steps:
      # 1.检出你在当前github工作空间的项目
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   # 具体参数 https://github.com/actions/checkout
      #   with:
      #     fetch-depth: 1

        # 2.安装node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        # 具体参数,以及支持的node版本 https://github.com/actions/setup-node
        with:
          node-version: 16

        # 3.打包
      - name: build
        run: npm i && npm run build

        # 4.运行semantic-release
      - name: Release
        # 需要的环境变量
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
  
  # 任务2
  release2:
    name: Release2
    runs-on: ubuntu-20.04
    steps:
      # 1.检出你在当前github工作空间的项目
      - name: Checkout
        uses: actions/checkout@v3
        # 具体参数 https://github.com/actions/checkout
        with:
          fetch-depth: 1